name: Swiftformat

on: pull_request

jobs:
  swiftformat:
    name: Check swiftformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Restore swift build cache
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm2-
          restore-keys: |
            ${{ runner.os }}-spm2-

      - name: swift build
        run: |
          if [ -d ".build" ]; then
            if ! [ -x "$(command -v swift-format)" ]; then
              sudo cp -f .build/release/swiftformat /usr/local/bin/swiftformat
            fi
          else
            git clone --depth 1 https://github.com/nicklockwood/SwiftFormat
            cd SwiftFormat
            swift build --disable-sandbox -c release
            mv .build .. && cd ..
            rm -rf SwiftFormat
            sudo cp -f .build/release/swiftformat /usr/local/bin/swiftformat
          fi

      - name: Run swiftformat
        run: swiftformat .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
